# Generated by Django 4.0.7 on 2022-09-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sessionplayer_name_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='graph_sprite_sheet',
            field=models.CharField(default='sprite_sheet.json', max_length=200),
        ),
    ]
